name: CI

on:
  pull_request:
  push:
    branches:
      - riscv
      - staging
      - trying

defaults:
  run:
    shell: bash

jobs:
  test:
    name: test
    runs-on: [self-hosted, ubuntu-20.04]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install -y gcc-riscv64-linux-gnu qemu-system-misc
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            override: true
            components: rust-src, rustfmt, clippy
      - name: Test
        run: ./ci/test.sh

  ci-success:
    name: ci
    if: github.event_name == 'push' && success()
    needs:
      - test
    runs-on: [self-hosted, ubuntu-20.04]
    steps:
      - name: Mark the job as a success
        run: exit 0
